//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoTerm
    {
        public int GO_ID { get; set; }
        public string name { get; set; }
        public string Go_definition { get; set; }
        public string ontology { get; set; }
    }
}
