//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using Models;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GoDBContext : DbContext
    {
        public GoDBContext()
            : base("name=GoDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GoTerm> GoTerms { get; set; }
        public virtual DbSet<HumanStruct> HumanStructs { get; set; }
        public virtual DbSet<is_a> is_a { get; set; }
        public virtual DbSet<part_of> part_of { get; set; }
    }
}
